#  appveyor.yml
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64'
  - SET PATH=%PATH%;C:\msys64\usr\bin

before_build:
  - copy windows_build_config.pl src\tools\msvc\config.pl
  - perl buildsetup.pl

build:
  project: pgsql.sln

test_script:
  - cd src\tools\msvc && vcregress check && vcregress bincheck

on_failure:
  - perl dumpregr.pl

configuration:
  - Release
